version: '2'
services:
    jenkins:
        volumes:
          - "./data:/data"
        build:
          context: ./
          dockerfile: Dockerfile-jenkins
        ports:
            - '127.0.0.1:8080:8080'
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'mHsJ33lF+1FZ'
        ports:
            - '127.0.0.1:3306:3306'

